swagger: '2.0'
info:
  title: Maxxidata API
  version: 1.0.0
  description: API do teste vaga fullstack Maxxidata
  contact:
    email: italospb7@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local
tags:
  - name: professional-type
    description: insert professional types
  - name: professional
    description: details of professional
paths:
  /professional-type:
    $ref: './paths/professional-type.yml'
  /professional:
    $ref: './paths/professional.yml'